CREATE TABLE  `vardi` (
 `id` INT( 5 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `lv` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
 `en` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
 `ru` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
 `kat` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;